[project]
name = "mcp-agent-experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agno>=1.2.6",
    "groq>=0.20.0",
    "mcp>=1.6.0",
]
